### ISSUE TITLE
Changes made in '.sw' file don't always update in-game & animated text appears broken.

### ISSUE THREAD

**Issue by Sturmivik** [thelightdesigner/ScuffedWalls#6]
I've been having theses problems for a day now. Whenever I make a change in the "_ScuffedWalls.sw" file, those changes don't always update in-game. Example, I'm messing around with TextToWall for lyrics and I add the "spreadspawntime" function, save it, and look at it in-game. But, I change my mind on it, so I remove the "spreadspawntime" function, save it, but when I load up the game again those same lyrics still act with the "spreadspawntime" function, even though it is no longer in the file.

My second problem is animated text that appears broken. When I want text to move in any direction, such as in a downward motion, the text breaks apart and looks like a mashed pile of moving rectangles. This is a sample of my animated text function, "animatedefiniteposition:[2.3,2,10,0],[2.3,0,10,1]". The interesting thing is when the text reaches its destination of coordinates, it pieces itself back together like it had never broke apart.

**Comment by thelightdesigner** [comment]
The first issue could be caused by a number of things other than ScuffedWalls. Make sure: your editor actually saved, ScuffedWalls actually reloaded (sometimes it freezes), and BeatSaber reloaded as well (sometimes it breaks, i've had this issue). If you can make a reproducible setup for the issue I will look into it.

The second issue is just a result of how `spreadspawntime` works. It adds or subtracts a random amount of time to each wall so that large groups of walls can jump in without creating a lag spike. If you want to control a group of walls with different durations and times, assign the walls a track and use AnimateTrack to control things like position, rotation, color, ect.

Hope this helps.

**Comment by Sturmivik** [comment]
I'll see if the issue keeps occurring once Noodle Extensions and Chroma are compatible with v1.16.3, and thank you for the AnimateTrack tip.

**Comment by Sturmivik** [comment]
I'm sorry, I just can't figure out my issue still. Certain commands are not getting updated after saving the file. The ScuffedWalls window shows that the work was saved, and written to the (difficulty).dat file and Info.dat file. And every time I want to test the map, I exit and reopen BeatSaber because refreshing the songs with "Ctrl + R" doesn't work to refresh the map.

What's even crazier is that whole lines of TextToWall functions don't actually appear in-game. Before BeatSaber got the 1.16.3 update, everything was appearing in-game, but now four whole lines of TextToWall functions don't appear at all. And I didn't touch those functions after the two new updates for BeatSaber were released.

If you would like to see the map file and SW file to test it, just let me know.
